In [1]:
import pandas as pd


df = pd.read_csv("data/customer_churn_dataset-training-master.csv")
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

### Remove unnecessary columns

In [2]:
df = df.drop(columns = ["CustomerID"]) # It contains no predictive information

In [3]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [4]:
df["Churn"].isnull().sum()

np.int64(1)

### Handle the missing target value for one observation

In [5]:
df = df.dropna(subset=["Churn"]) # Remove observations with missing target values

### 
One observation contained missing value the target variable Churn. Since supervised learning models require known target labels, this observation was removed prior to model development.

### Separate features and target

In [6]:
X = df.drop("Churn",axis=1)
y=df["Churn"]

In [7]:
categorical_cols = [ "Gender", "Subscription Type","Contract Length"]

### One-Hot Encoding

In [8]:
X = pd.get_dummies(X, columns = categorical_cols , drop_first=True )

### Train-Test Split

In [9]:

from sklearn.model_selection import train_test_split

X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify= y) # Using stratify=y preserves the churn distribution in both sets.

### Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() # creates a scaling object

scaler.fit(X_train) # Learn the statistics of the training data 
X_train_scaled = scaler.transform(X_train) # Use the learned statistics to scale the training data
X_test_scaled = scaler.transform(X_test) # Reuse the same mean and std from training data and Scale test data using those values.

### Save processed datasets

In [11]:
import os

os.makedirs("data/processed", exist_ok=True)

pd.DataFrame(X_train_scaled).to_csv(
    "data/processed/X_train_scaled.csv",
    index=False
)

pd.DataFrame(X_test_scaled).to_csv(
    "data/processed/X_test_scaled.csv",
    index=False
)

y_train.to_csv(
    "data/processed/y_train.csv",
    index=False
)

y_test.to_csv(
    "data/processed/y_test.csv",
    index=False
)

X_train.to_csv(
    "data/processed/X_train_features.csv",
    index=False
)